insert into estados (id, sigla, nome) values ('11','RO','Rondônia');
insert into estados (id, sigla, nome) values ('12','AC','Acre');
insert into estados (id, sigla, nome) values ('13','AM','Amazonas');
insert into estados (id, sigla, nome) values ('14','RR','Roraima');
insert into estados (id, sigla, nome) values ('15','PA','Pará');
insert into estados (id, sigla, nome) values ('16','AP','Amapá');
insert into estados (id, sigla, nome) values ('17','TO','Tocantins');
insert into estados (id, sigla, nome) values ('21','MA','Maranhão');
insert into estados (id, sigla, nome) values ('22','PI','Piauí');
insert into estados (id, sigla, nome) values ('23','CE','Ceará');
insert into estados (id, sigla, nome) values ('24','RN','Rio Grande do Norte');
insert into estados (id, sigla, nome) values ('25','PB','Paraíba');
insert into estados (id, sigla, nome) values ('26','PE','Pernambuco');
insert into estados (id, sigla, nome) values ('27','AL','Alagoas');
insert into estados (id, sigla, nome) values ('28','SE','Sergipe');
insert into estados (id, sigla, nome) values ('29','BA','Bahia');
insert into estados (id, sigla, nome) values ('31','MG','Minas Gerais');
insert into estados (id, sigla, nome) values ('32','ES','Espírito Santo');
insert into estados (id, sigla, nome) values ('33','RJ','Rio de Janeiro');
insert into estados (id, sigla, nome) values ('35','SP','São Paulo');
insert into estados (id, sigla, nome) values ('41','PR','Paraná');
insert into estados (id, sigla, nome) values ('42','SC','Santa Catarina');
insert into estados (id, sigla, nome) values ('43','RS','Rio Grande do Sul');
insert into estados (id, sigla, nome) values ('50','MS','Mato Grosso do Sul');
insert into estados (id, sigla, nome) values ('51','MT','Mato Grosso');
insert into estados (id, sigla, nome) values ('52','GO','Goiás');
insert into estados (id, sigla, nome) values ('53','DF','Distrito Federal');